apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nyx0fjs34-go
  janus-idp.io/tekton: nyx0fjs34-go
  backstage.io/kubernetes-id: nyx0fjs34-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nyx0fjs34-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
