apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nyx0fjs34-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nyx0fjs34-go 
  name: nyx0fjs34-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nyx0fjs34-go 
